import { SERVER_PROPS_ID } from "next/dist/shared/lib/constants"
import Nav from "./Nav"
import './globals.css'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const getArticle = async () =>{
  var url = 'https://api.currentsapi.services/v1/search?langauge=us&apiKey=_nzV85Gpfc5q7Qq_QuQ1rLNUTSKIh9r7uOtBD-ZLnczq0qNm';

  const res = await fetch(url);
  return await res.json()
}

 
export default async function RootLayout({ children, params }) {
  const articles =  await getArticle();

  params.articles = articles;


 return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
