import Nav from "./Nav"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
